INSERT INTO "OlimpiColombiaSite_modalidad" (nombre, deporte_id) VALUES ('Atletismo 100m con vallas femenino', 1);
INSERT INTO "OlimpiColombiaSite_modalidad" (nombre, deporte_id) VALUES ('Atletismo 100m femenino', 1);
INSERT INTO "OlimpiColombiaSite_modalidad" (nombre, deporte_id) VALUES ('Atletismo 110m con vallas masculino', 1);
INSERT INTO "OlimpiColombiaSite_modalidad" (nombre, deporte_id) VALUES ('Atletismo 1500m femenino', 1);
INSERT INTO "OlimpiColombiaSite_modalidad" (nombre, deporte_id) VALUES ('Atletismo 200m masculino', 1);
INSERT INTO "OlimpiColombiaSite_modalidad" (nombre, deporte_id) VALUES ('Atletismo 3000m con obstáculos femenino', 1);
INSERT INTO "OlimpiColombiaSite_modalidad" (nombre, deporte_id) VALUES ('Atletismo 400m masculino', 1);
INSERT INTO "OlimpiColombiaSite_modalidad" (nombre, deporte_id) VALUES ('Atletismo 800m masculino', 1);
INSERT INTO "OlimpiColombiaSite_modalidad" (nombre, deporte_id) VALUES ('Atletismo Heptatlón femenino', 1);
INSERT INTO "OlimpiColombiaSite_modalidad" (nombre, deporte_id) VALUES ('Atletismo Lanzamiento de bala femenino', 1);
INSERT INTO "OlimpiColombiaSite_modalidad" (nombre, deporte_id) VALUES ('Atletismo Lanzamiento de disco masculino', 1);
INSERT INTO "OlimpiColombiaSite_modalidad" (nombre, deporte_id) VALUES ('Atletismo Lanzamiento de jabalina femenino', 1);
INSERT INTO "OlimpiColombiaSite_modalidad" (nombre, deporte_id) VALUES ('Atletismo Maratón femenino', 1);
INSERT INTO "OlimpiColombiaSite_modalidad" (nombre, deporte_id) VALUES ('Atletismo Maratón masculino', 1);
INSERT INTO "OlimpiColombiaSite_modalidad" (nombre, deporte_id) VALUES ('Atletismo Marcha atlética 20km femenina', 1);
INSERT INTO "OlimpiColombiaSite_modalidad" (nombre, deporte_id) VALUES ('Atletismo Marcha atlética 20km masculina', 1);
INSERT INTO "OlimpiColombiaSite_modalidad" (nombre, deporte_id) VALUES ('Atletismo Marcha atlética 50km masculina', 1);
INSERT INTO "OlimpiColombiaSite_modalidad" (nombre, deporte_id) VALUES ('Atletismo Relevo 4x400m masculino', 1);
INSERT INTO "OlimpiColombiaSite_modalidad" (nombre, deporte_id) VALUES ('Atletismo Salto triple femenino', 1);
INSERT INTO "OlimpiColombiaSite_modalidad" (nombre, deporte_id) VALUES ('Atletismo Salto triple masculino', 1);
INSERT INTO "OlimpiColombiaSite_modalidad" (nombre, deporte_id) VALUES ('Boxeo Peso medio masculino (75kg)', 2);
INSERT INTO "OlimpiColombiaSite_modalidad" (nombre, deporte_id) VALUES ('Boxeo Peso minimosca masculino (46-49kg)', 2);
INSERT INTO "OlimpiColombiaSite_modalidad" (nombre, deporte_id) VALUES ('Boxeo Peso mosca femenino (48-51kg)', 2);
INSERT INTO "OlimpiColombiaSite_modalidad" (nombre, deporte_id) VALUES ('Boxeo Peso mosca masculino (52kg)', 2);
INSERT INTO "OlimpiColombiaSite_modalidad" (nombre, deporte_id) VALUES ('Boxeo Peso semipesado masculino (81kg)', 2);
INSERT INTO "OlimpiColombiaSite_modalidad" (nombre, deporte_id) VALUES ('Ciclismo BMX BMX femenino', 3);
INSERT INTO "OlimpiColombiaSite_modalidad" (nombre, deporte_id) VALUES ('Ciclismo BMX BMX masculino', 3);
INSERT INTO "OlimpiColombiaSite_modalidad" (nombre, deporte_id) VALUES ('Ciclismo de montaña Cross country masculino', 4);
INSERT INTO "OlimpiColombiaSite_modalidad" (nombre, deporte_id) VALUES ('Ciclismo de pista Keirin femenino', 5);
INSERT INTO "OlimpiColombiaSite_modalidad" (nombre, deporte_id) VALUES ('Ciclismo de pista Keirin masculino', 5);
INSERT INTO "OlimpiColombiaSite_modalidad" (nombre, deporte_id) VALUES ('Ciclismo de pista Ómnium masculino', 5);
INSERT INTO "OlimpiColombiaSite_modalidad" (nombre, deporte_id) VALUES ('Ciclismo de pista Velocidad femenino', 5);
INSERT INTO "OlimpiColombiaSite_modalidad" (nombre, deporte_id) VALUES ('Ciclismo de pista Velocidad masculino', 5);
INSERT INTO "OlimpiColombiaSite_modalidad" (nombre, deporte_id) VALUES ('Ciclismo de ruta Carrera de ruta femenina', 6);
INSERT INTO "OlimpiColombiaSite_modalidad" (nombre, deporte_id) VALUES ('Ciclismo de ruta Carrera de ruta masculina', 6);
INSERT INTO "OlimpiColombiaSite_modalidad" (nombre, deporte_id) VALUES ('Ciclismo de ruta Contrarreloj individual masculino', 6);
INSERT INTO "OlimpiColombiaSite_modalidad" (nombre, deporte_id) VALUES ('Clavados Plataforma 10m masculino', 7);
INSERT INTO "OlimpiColombiaSite_modalidad" (nombre, deporte_id) VALUES ('Clavados Trampolín 3m femenino', 7);
INSERT INTO "OlimpiColombiaSite_modalidad" (nombre, deporte_id) VALUES ('Clavados Trampolín 3m masculino', 7);
INSERT INTO "OlimpiColombiaSite_modalidad" (nombre, deporte_id) VALUES ('Ecuestre Salto individual', 8);
INSERT INTO "OlimpiColombiaSite_modalidad" (nombre, deporte_id) VALUES ('Esgrima Espada individual masculina', 9);
INSERT INTO "OlimpiColombiaSite_modalidad" (nombre, deporte_id) VALUES ('Esgrima Florete individual femenino', 9);
INSERT INTO "OlimpiColombiaSite_modalidad" (nombre, deporte_id) VALUES ('Fútbol Femenino', 10);
INSERT INTO "OlimpiColombiaSite_modalidad" (nombre, deporte_id) VALUES ('Fútbol Masculino', 10);
INSERT INTO "OlimpiColombiaSite_modalidad" (nombre, deporte_id) VALUES ('Gimnasia artística Anillas - masculino', 11);
INSERT INTO "OlimpiColombiaSite_modalidad" (nombre, deporte_id) VALUES ('Gimnasia artística Barra fija - masculino', 11);
INSERT INTO "OlimpiColombiaSite_modalidad" (nombre, deporte_id) VALUES ('Gimnasia artística Barras asimétricas - femenino', 11);
INSERT INTO "OlimpiColombiaSite_modalidad" (nombre, deporte_id) VALUES ('Gimnasia artística Barras paralelas - masculino', 11);
INSERT INTO "OlimpiColombiaSite_modalidad" (nombre, deporte_id) VALUES ('Gimnasia artística Competencia múltiple - femenino', 11);
INSERT INTO "OlimpiColombiaSite_modalidad" (nombre, deporte_id) VALUES ('Gimnasia artística Competencia múltiple - masculino', 11);
INSERT INTO "OlimpiColombiaSite_modalidad" (nombre, deporte_id) VALUES ('Gimnasia artística Femenino', 11);
INSERT INTO "OlimpiColombiaSite_modalidad" (nombre, deporte_id) VALUES ('Gimnasia artística Masculino', 11);
INSERT INTO "OlimpiColombiaSite_modalidad" (nombre, deporte_id) VALUES ('Gimnasia artística Salto - masculino', 11);
INSERT INTO "OlimpiColombiaSite_modalidad" (nombre, deporte_id) VALUES ('Gimnasia artística Suelo - femenino', 11);
INSERT INTO "OlimpiColombiaSite_modalidad" (nombre, deporte_id) VALUES ('Gimnasia artística Suelo - masculino', 11);
INSERT INTO "OlimpiColombiaSite_modalidad" (nombre, deporte_id) VALUES ('Gimnasia artística Viga de equilibrio - femenino', 11);
INSERT INTO "OlimpiColombiaSite_modalidad" (nombre, deporte_id) VALUES ('Golf Stroke play individual femenino', 12);
INSERT INTO "OlimpiColombiaSite_modalidad" (nombre, deporte_id) VALUES ('Judo Hasta 57 kg femenino', 13);
INSERT INTO "OlimpiColombiaSite_modalidad" (nombre, deporte_id) VALUES ('Judo Hasta 70 kg femenino', 13);
INSERT INTO "OlimpiColombiaSite_modalidad" (nombre, deporte_id) VALUES ('Levantamiento de pesas 56kg masculino', 14);
INSERT INTO "OlimpiColombiaSite_modalidad" (nombre, deporte_id) VALUES ('Levantamiento de pesas 58kg femenino', 14);
INSERT INTO "OlimpiColombiaSite_modalidad" (nombre, deporte_id) VALUES ('Levantamiento de pesas 62kg masculino', 14);
INSERT INTO "OlimpiColombiaSite_modalidad" (nombre, deporte_id) VALUES ('Levantamiento de pesas 63kg femenino', 14);
INSERT INTO "OlimpiColombiaSite_modalidad" (nombre, deporte_id) VALUES ('Levantamiento de pesas 69kg femenino', 14);
INSERT INTO "OlimpiColombiaSite_modalidad" (nombre, deporte_id) VALUES ('Levantamiento de pesas 69kg masculino', 14);
INSERT INTO "OlimpiColombiaSite_modalidad" (nombre, deporte_id) VALUES ('Levantamiento de pesas 75kg femenino', 14);
INSERT INTO "OlimpiColombiaSite_modalidad" (nombre, deporte_id) VALUES ('Levantamiento de pesas 77kg masculino', 14);
INSERT INTO "OlimpiColombiaSite_modalidad" (nombre, deporte_id) VALUES ('Lucha de estilo libre, 48 kg femenino', 15);
INSERT INTO "OlimpiColombiaSite_modalidad" (nombre, deporte_id) VALUES ('Lucha Lucha de estilo libre, 58 kg femenino', 15);
INSERT INTO "OlimpiColombiaSite_modalidad" (nombre, deporte_id) VALUES ('Lucha Lucha de estilo libre, 74 kg masculino', 15);
INSERT INTO "OlimpiColombiaSite_modalidad" (nombre, deporte_id) VALUES ('Lucha Lucha de estilo libre, 75 kg femenino', 15);
INSERT INTO "OlimpiColombiaSite_modalidad" (nombre, deporte_id) VALUES ('Lucha Lucha Grecorromana, 75 kg masculino', 15);
INSERT INTO "OlimpiColombiaSite_modalidad" (nombre, deporte_id) VALUES ('Nado sincronizado Duetos', 16);
INSERT INTO "OlimpiColombiaSite_modalidad" (nombre, deporte_id) VALUES ('Natación 100m braza masculino', 17);
INSERT INTO "OlimpiColombiaSite_modalidad" (nombre, deporte_id) VALUES ('Natación 200m braza masculino', 17);
INSERT INTO "OlimpiColombiaSite_modalidad" (nombre, deporte_id) VALUES ('Natación 200m espalda masculino', 17);
INSERT INTO "OlimpiColombiaSite_modalidad" (nombre, deporte_id) VALUES ('Natación 200m mariposa masculino', 17);
INSERT INTO "OlimpiColombiaSite_modalidad" (nombre, deporte_id) VALUES ('Natación 50m estilo libre femenino', 17);
INSERT INTO "OlimpiColombiaSite_modalidad" (nombre, deporte_id) VALUES ('Rugby a siete Femenino', 18);
INSERT INTO "OlimpiColombiaSite_modalidad" (nombre, deporte_id) VALUES ('Taekwondo -57kg femenino', 19);
INSERT INTO "OlimpiColombiaSite_modalidad" (nombre, deporte_id) VALUES ('Taekwondo -58kg masculino', 19);
INSERT INTO "OlimpiColombiaSite_modalidad" (nombre, deporte_id) VALUES ('Tenis de mesa Individual femenino', 20);
INSERT INTO "OlimpiColombiaSite_modalidad" (nombre, deporte_id) VALUES ('Tenis Dobles masculinos', 21);
INSERT INTO "OlimpiColombiaSite_modalidad" (nombre, deporte_id) VALUES ('Tenis Dobles mixtos', 21);
INSERT INTO "OlimpiColombiaSite_modalidad" (nombre, deporte_id) VALUES ('Tenis Individual femenino', 21);
INSERT INTO "OlimpiColombiaSite_modalidad" (nombre, deporte_id) VALUES ('Tiro con arco Competencia individual femenina', 23);
INSERT INTO "OlimpiColombiaSite_modalidad" (nombre, deporte_id) VALUES ('Tiro con arco Competencia individual masculina', 23);
INSERT INTO "OlimpiColombiaSite_modalidad" (nombre, deporte_id) VALUES ('Tiro con arco Competencia por equipos femenina', 23);
INSERT INTO "OlimpiColombiaSite_modalidad" (nombre, deporte_id) VALUES ('Tiro Fosa masculino', 22);
INSERT INTO "OlimpiColombiaSite_modalidad" (nombre, deporte_id) VALUES ('Vela RS:X masculino', 24);
