# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2016-08-21 13:32
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('OlimpiColombiaSite', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Atleta',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombres', models.CharField(max_length=200)),
                ('lugar_nacimiento', models.CharField(max_length=100)),
                ('fecha_nacimiento', models.DateField()),
                ('edad', models.IntegerField()),
                ('peso', models.DecimalField(decimal_places=1, help_text='Peso en kilogramos (kg)', max_digits=4)),
                ('estatura', models.DecimalField(decimal_places=1, help_text='Estatura en centimetros (cm)', max_digits=4)),
                ('fotografia', models.CharField(help_text='URL de la imagen del atleta', max_length=1000, verbose_name='Fotografía')),
                ('video_destacado', models.FileField(null=True, upload_to='')),
            ],
        ),
        migrations.CreateModel(
            name='Competencia',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fecha', models.DateTimeField()),
                ('descripcion', models.CharField(blank=True, max_length=200, verbose_name='Descripción')),
            ],
        ),
        migrations.CreateModel(
            name='Entrenador',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombres', models.CharField(max_length=200)),
            ],
            options={
                'verbose_name_plural': 'Entrenadores',
            },
        ),
        migrations.CreateModel(
            name='Highlight',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('video', models.FileField(upload_to='')),
                ('atleta', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='OlimpiColombiaSite.Atleta')),
                ('competencia', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='OlimpiColombiaSite.Competencia')),
            ],
        ),
        migrations.CreateModel(
            name='Imagen',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('url', models.CharField(max_length=1000)),
            ],
        ),
        migrations.CreateModel(
            name='Modalidad',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=70)),
            ],
            options={
                'verbose_name_plural': 'Modalidades',
            },
        ),
        migrations.CreateModel(
            name='Resultado',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('resultado', models.CharField(blank=True, max_length=100)),
                ('video', models.FileField(null=True, upload_to='')),
                ('atleta', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='OlimpiColombiaSite.Atleta')),
                ('competencia', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='OlimpiColombiaSite.Competencia')),
            ],
        ),
        migrations.AddField(
            model_name='deporte',
            name='descripcion',
            field=models.CharField(blank=True, max_length=1000, verbose_name='Descripción'),
        ),
        migrations.AlterField(
            model_name='deporte',
            name='imagen',
            field=models.CharField(help_text='URL de la imagen del deporte', max_length=1000, verbose_name='Imágen'),
        ),
        migrations.AddField(
            model_name='modalidad',
            name='deporte',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='OlimpiColombiaSite.Deporte'),
        ),
        migrations.AddField(
            model_name='competencia',
            name='modalidad',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='OlimpiColombiaSite.Modalidad'),
        ),
        migrations.AddField(
            model_name='atleta',
            name='deporte',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='OlimpiColombiaSite.Deporte'),
        ),
        migrations.AddField(
            model_name='atleta',
            name='entrenador',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='OlimpiColombiaSite.Entrenador'),
        ),
    ]
