# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2016-08-20 21:53
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('OlimpiColombiaSite', '0003_initial_data_deporte'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='competencia',
            name='rival',
        ),
        migrations.RemoveField(
            model_name='competencia',
            name='video_destacado',
        ),
        migrations.AddField(
            model_name='competencia',
            name='participantes',
            field=models.ManyToManyField(to='OlimpiColombiaSite.Atleta'),
        ),
        migrations.AlterField(
            model_name='atleta',
            name='fotografia',
            field=models.ImageField(max_length=1000, upload_to=''),
        ),
    ]
