# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2016-08-20 22:23
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('OlimpiColombiaSite', '0004_auto_20160820_1653'),
    ]

    operations = [
        migrations.CreateModel(
            name='Highlight',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('video', models.FileField(upload_to='')),
                ('atleta', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='OlimpiColombiaSite.Atleta')),
            ],
        ),
        migrations.RemoveField(
            model_name='competencia',
            name='hora',
        ),
        migrations.AlterField(
            model_name='competencia',
            name='fecha',
            field=models.DateTimeField(),
        ),
        migrations.AddField(
            model_name='highlight',
            name='competencia',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='OlimpiColombiaSite.Competencia'),
        ),
    ]
