# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2016-08-21 03:22
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('OlimpiColombiaSite', '0005_auto_20160820_1723'),
    ]

    operations = [
        migrations.CreateModel(
            name='Entrenador',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombres', models.CharField(max_length=200)),
            ],
        ),
        migrations.CreateModel(
            name='Resultado',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('resultado', models.CharField(max_length=100)),
                ('video', models.FileField(upload_to=b'')),
            ],
        ),
        migrations.RemoveField(
            model_name='competencia',
            name='participantes',
        ),
        migrations.RemoveField(
            model_name='competencia',
            name='resultado',
        ),
        migrations.RemoveField(
            model_name='modalidad',
            name='atleta',
        ),
        migrations.RemoveField(
            model_name='modalidad',
            name='entrenador',
        ),
        migrations.RemoveField(
            model_name='modalidad',
            name='medalla',
        ),
        migrations.AddField(
            model_name='atleta',
            name='deporte',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='OlimpiColombiaSite.Deporte'),
        ),
        migrations.AddField(
            model_name='competencia',
            name='descripcion',
            field=models.CharField(blank=True, max_length=200),
        ),
        migrations.AddField(
            model_name='competencia',
            name='hora',
            field=models.TimeField(null=True),
        ),
        migrations.AlterField(
            model_name='atleta',
            name='fotografia',
            field=models.CharField(max_length=1000),
        ),
        migrations.AlterField(
            model_name='atleta',
            name='video_destacado',
            field=models.FileField(null=True, upload_to=b''),
        ),
        migrations.AddField(
            model_name='resultado',
            name='atleta',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='OlimpiColombiaSite.Atleta'),
        ),
        migrations.AddField(
            model_name='resultado',
            name='competencia',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='OlimpiColombiaSite.Competencia'),
        ),
        migrations.AddField(
            model_name='atleta',
            name='entrenador',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='OlimpiColombiaSite.Entrenador'),
        ),
    ]
